### ISSUE TITLE
Open to releasing a new version?

### ISSUE THREAD

**Issue by bachand** [raspu/Highlightr#104]
Thank you for sharing this very useful project, @raspu ! I wanted to see if you would be open to publishing a new release? The [last release](https://github.com/raspu/Highlightr/releases/tag/2.1.2) was published in 2021 with the latest change from 2020. I see that there have been a number of updates to the project since this then which made me think that it could be nice to roll those changes up into a new release!

**Comment by bachand** [comment]
In this case, my team is interested in consuming a new release via SPM.

**Comment by angiemugo** [comment]
Our project would also really benefit from this. We've forked the repo and added some languages on top of it meanwhile. I am open to collaborating on this in case @raspu needs some extra hands. Thanks @raspu  for this tool, we are really enjoying working on it.

**Comment by raspu** [comment]
Hi @angiemugo @bachand I am happy you are finding the project useful :). I'll happily make a new release, but I want to update highlight.js as well and I am really having issues finding the time to do it. So if any of you would like to do it, I'll happily make you collaborators, as I need more hands to keep the project up to date. Let me know!

**Comment by raspu** [comment]
@angiemugo I just sent you an invite!

**Comment by angiemugo** [comment]
I have a PR [here](https://github.com/raspu/Highlightr/pull/105).

**Comment by raspu** [comment]
2.2.0 was released :).
CC: @angiemugo @bachand Thanks for suggesting & helping.
