### ISSUE TITLE
I met some crash: JavaScriptCore`WTF::CrashOnOverflow::crash:

### ISSUE THREAD

**Issue by purkylin** [raspu/Highlightr#20]
JavaScriptCore`WTF::CrashOnOverflow::crash:

**Comment by raspu** [comment]
Hi @purkylin, do you have a full stack trace, or more detail about what was happening when you saw this crash? Also, was this on macOS or in iOS, and what kind of device? 

Now, this is an overflow, where you trying to highligt a really long code?

**Comment by purkylin** [comment]
Not too long.
Only occurs when my iPhone connect to my Mac, any the safari auto connect is enabled

**Comment by raspu** [comment]
@purkylin That is not enough information to start investigate this, do you have a full stacktrace? or steps to reproduce?
