### ISSUE TITLE
Swift 4 and Xcode 9 Compatible?

### ISSUE THREAD

**Issue by GrfxGuru** [raspu/Highlightr#24]
I am having a problem getting this to work with Swift 4 in Xcode 9. Can anyone confirm that has yet to be updated to support compilation for those versions?

This seems like a great idea!

Thanks.

**Comment by andypiper** [comment]
It has not been updated for Swift 4 so far, as far as I can tell...

**Comment by raspu** [comment]
Hi guys, sorry for the delay. There's some work on the swift4 branch, but I don't think is ready for production. Tbh I don't have the time to work on this nowadays, so I am very open to pull requests.

**Comment by raspu** [comment]
Also, take a look at what @brunophilipe is doing [here](brunophilipe).

**Comment by GrfxGuru** [comment]
Thanks @raspu for the update and pointer. If I get time I will try and help out.

**Comment by raspu** [comment]
You are welcome :).
