### ISSUE TITLE
How to install Highlightr without issues?

### ISSUE THREAD

**Issue by welljsjs** [raspu/Highlightr#25]
Hey, I installed 'Highlightr' the following way: 

<code>
    cd "My_App" 
</code><br>
<code>
    pod init
</code><br>
Edited Podfile: <br>
<pre>
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'My_Target' do
    pod 'Quick'
    pod 'Nimble'
    pod 'Highlightr'
end<br>
</pre>I only want to use Highlightr for OSX. <br>
<code>
pod install
</code><br>Successful install is said in terminal.
Open my_app.xworkspace...
Building....
Build failed due to 23 issues, all related to Highlightr, f.ex. the first one saying "Swift Compiler Error"
<code>
"[...]/Highlightr/Pod/Classes/CodeAttributedString.swift:93:24: Method does not override any method from its superclass"</code>

It's probably my mistake, but I don't know what to do. Could you help me out? Couldn't find any install instruction on the internet.

Thanks in advance!

**Comment by rudedogg** [comment]
I'm not sure it's required, but does adding the platform to the podfile work?

```
platform :osx, '10.12'
```

**Comment by welljsjs** [comment]
@rudedogg Unluckily, does not seem to help. Still 23 errors displayed.

**Comment by rudedogg** [comment]
@welljsjs Are the errors related to Swift 4? In Xcoe, if you go to the "Pods" project inside your project's workspace, does the Highlightr target have a build setting for the swift version?

**Comment by welljsjs** [comment]
That looks good! Setting the swift version to 3.2 removed all errors.
Hopefully Highlightr will support Swift 4 soon. 

Thanks a lot for your help! 😃

**Comment by rudedogg** [comment]
@welljsjs Awesome! No problem.

You'll have to do the same thing if you run `pod update` unfortunately. Hopefully this will be fixed soon by either https://github.com/CocoaPods/CocoaPods/issues/7134 or a PR to update Highlightr to Swift 4

**Comment by raspu** [comment]
Guys, I am closing this issue, I created #26 as a follow up.
