### ISSUE TITLE
required version is too high

### ISSUE THREAD

**Issue by purkylin** [raspu/Highlightr#31]

**Comment by raspu** [comment]
Required version of what, sorry?

**Comment by purkylin** [comment]
10.0

J.P. Illanes <notifications@github.com>于2018年1月2日 周二下午11:03写道：

**Comment by purkylin** [comment]
purkylin <purkylin@gmail.com>于2018年1月4日 周四下午8:44写道：

**Comment by raspu** [comment]
Min iOS Version required: 8.0
Min macOS Version required: 10.11
