### ISSUE TITLE
Color of text not updating when changing theme

### ISSUE THREAD

**Issue by facundomedica** [raspu/Highlightr#4]
I'm testing the sample app, I've found that adding `self.textStorage.language = self.textStorage.language` makes the color of the text update.

Maybe consider adding a function that makes: `highlight(NSMakeRange(0, stringStorage.length))` when theme is changed?

**Comment by raspu** [comment]
I see your point, and it would be nice to make this behavior consistent. I have two possible solutions: 

**1.**  Stop exposing `highlightr` inside `CodeAttributedString`, and make a façade with all the useful methods and props exposed directly in `CodeAttributedString`. 
**2.**  Make `highlightr` KVO compatible (Probably I'll do this in the future anyway) and listen for changes on the theme property. 

I like option **1** better, but I will give it some thought on how to make it properly. 

Thanks for reporting this, by the way :).
