### ISSUE TITLE
[v2.1.0] Some code files are not highlighted

### ISSUE THREAD

**Issue by jkpang** [raspu/Highlightr#60]
Hello, I'm trying to load this code text:
https://raw.githubusercontent.com/brianegan/fancy_network_image/master/lib/fancy_network_image.dart
```
let code = try! String(contentsOf: URL(string: "https://raw.githubusercontent.com/brianegan/fancy_network_image/master/lib/fancy_network_image.dart")!)
textView.text = code
textStorage.language = "dart"
highlightr = textStorage.highlightr
```
But after I replaced the **highlight.min.js** file in v2.0.1 with v2.1.0, the code was successfully highlighted.
So I think it is an error caused by **highlight.min.js** in v2.1.0.
Thank you very much for your open source！

The result is shown below: 
![image](https://user-images.githubusercontent.com/17583451/53241999-6d8b5c00-36de-11e9-89d8-0b850d4e683f.png)

**Comment by raspu** [comment]
Interesting, I assume the problem is with highlight.js. Let me try with the latest version.

**Comment by Kidsmile88** [comment]
It is so beautiful. perhaps less boring than working with it. 😊
