### ISSUE TITLE
Does not work with Xcode 11

### ISSUE THREAD

**Issue by catilac** [raspu/Highlightr#74]
Some of the code is incompatible with swift 4.2
Happy to help with some direction, I've never worked in this codebase though. Is anyone working on this?

**Comment by funkenstrahlen** [comment]
I just added the Pod in Xcode 11.2 and it works fine.

**Comment by catilac** [comment]
@funkenstrahlen ooh really? Okay, I'll give this another try soon.

**Comment by RobertoMachorro** [comment]
I have a Pull Request pending that brings it up to Xcode 12: #73
