### ISSUE TITLE
Abandoned? 

### ISSUE THREAD

**Issue by appfrilans** [raspu/Highlightr#75]
Is this project abandoned? Have not seen to be any updates last year and no pull requests are merged?

**Comment by catilac** [comment]
Definitely abandoned. I'm going to use highlight.js inside of a webview and see how it goes.

**Comment by RobertoMachorro** [comment]
I currently use this for my [text editor](https://github.com/RobertoMachorro/Moped), so I've been keeping a brach/PR (#73) going with updates. Feel free to use the PR or my fork directly (same code).

**Comment by AdamBCo** [comment]
@raspu Any update on this?

**Comment by RobertoMachorro** [comment]
I can't speak on behalf of @raspu, however I follow the master branch for this repo closely (I have a fork). He has been busy lately merging Pull Requests in December, so I don't believe the project to be abandoned, just slow.

**Comment by raspu** [comment]
Hi guys, I think it's quite obvious I am no longer maintaining this, I am super sorry about that. I can add contributors if any of you would like to keep it alive, I'd really appreciate it a lot. If not you can use some of the forks that are more up to date.

**Comment by RobertoMachorro** [comment]
@raspu sorry to hear this, I have a fork and I'm willing to contribute on the project - however, I would be unable to lead due to the level of commitments I currently have.

**Comment by raspu** [comment]
@RobertoMachorro That's alright, if you can help maintain it that's more than enough. I will add you as a contributor.
