### ISSUE TITLE
How to make scrollable in macOS

### ISSUE THREAD

**Issue by fadielse** [raspu/Highlightr#77]
Hi this library is cool..
but i got problem when i want to make NSTextview scrollable when the the text is over the height of textview. how to make it possible? 
I have done many experiments but it still hasn't worked

thanks

**Comment by codeshif** [comment]
Can you send a screenshot ?

**Comment by RobertoMachorro** [comment]
I'm not sure I understand what you are trying to do, maybe upload a video or screenshots?
I currently use Highlightr in my [text editor](https://github.com/RobertoMachorro/Moped) with no scroll issues.

**Comment by Panway** [comment]
I just had the same problem as you, and solved it through the following ways:
``` swift
let textContainer = NSTextContainer(size: CGSize(width: self.view.bounds.width, height: .greatestFiniteMagnitude))
```

Hope this helps those new to Highlightr
