### ISSUE TITLE
How to add new languages?

### ISSUE THREAD

**Issue by ActuallyZach** [raspu/Highlightr#78]
### Problem
I have tried to replace the Highlight.min.js with a new file generated from compiling Highlight.js with the command 
`node tools/build.js jelly swift json javascript`
This outputs a highlight.min.js file. When I replace the highlight.min.js file inside of Highlightr, it returns nil after instantiating the Highlightr class.
### Question
How should I go about adding languages? Is there a different command I have to run inside the Highlight.js project or is there a completely different way of adding languages for this fork?

**Comment by nkleemann** [comment]
@ActuallyTaylor Did you find a way of adding new languages?

**Comment by ActuallyTaylor** [comment]
@nkleemann I did not, I moved on to creating my own text editor for iOS

**Comment by raspu** [comment]
Well, sorry for not replying to this 😓... When I was still maintaining this I was using this to build it: 

```js
node tools/build.js -t cdn 
```
Make sure you use the `cdn` variant, as we don't want the library to expect a browser environment. I really hope this still works!
