### ISSUE TITLE
Which version does SPM support? 

### ISSUE THREAD

**Issue by sniperboy0829** [raspu/Highlightr#84]
when I use version 2.1.1 SPM tips "has no Package.swift manifest"

<img width="643" alt="Screen Shot 2021-04-22 at 14 17 48" src="https://user-images.githubusercontent.com/79051801/115666063-aedb2d00-a376-11eb-9c41-3b589ff3efa3.png">

**Comment by sniperboy0829** [comment]
![Uploading Screen Shot 2021-04-22 at 14.17.48.png…]()

**Comment by raspu** [comment]
I just tagged 2.1.2.
