### ISSUE TITLE
Bump Highlight.js version

### ISSUE THREAD

**Issue by nkleemann** [raspu/Highlightr#94]
I need support for syntax highlighting in Haskell source files. Haskell is supported in Highlight.js on the [main branch](https://github.com/highlightjs/highlight.js/blob/main/src/languages/haskell.js). 

Can you bump the bundled highlight.js version?

**Comment by raspu** [comment]
@nkleemann Did you tried [this](https://github.com/raspu/Highlightr/issues/78#issuecomment-1472228225)?

**Comment by nkleemann** [comment]
Sorry, not yet. Highlightr is many branches deep in the dependency tree I'm working with and I don't have the time right now to update manually. Also I found a good replacement for my code editor package needs [here](https://github.com/ActuallyTaylor/Firefly). 

Maybe we should keep this issue open for people of the future that depend on newer `Highlight.js` versions?

**Comment by raspu** [comment]
@nkleemann I'll try to update it myself these days.

**Comment by dehesa** [comment]
That would be amazing. I would also love a new version.
